/* Host-side unit test runner for KeSp firmware */
#include "test_framework.h"

/* Shared test counters */
int _test_pass_count = 0;
int _test_fail_count = 0;

/* Test suite declarations */
extern void test_key_stats(void);
extern void test_bigram(void);
extern void test_board_config(void);
extern void test_matrix_constants(void);
extern void test_matrix_flag(void);
extern void test_led_anim_constants(void);
extern void test_oled_nav(void);
extern void test_keymap_nvs(void);
extern void test_keycodes(void);
extern void test_key_features(void);
extern void test_tap_hold(void);
extern void test_tap_dance(void);
extern void test_combo(void);
extern void test_leader(void);
extern void test_rf_packet(void);
extern void test_rf_slot(void);
extern void test_heartbeat(void);
extern void test_trackpad_map(void);
extern void test_trackpad_accel_curve(void);
extern void test_trackpad_cfg(void);
extern void test_rf_pairing(void);
extern void test_rf_pairing_declared_slot(void);
extern void test_rf_signal_q255(void);
extern void test_cdc_monitor(void);
extern void test_cdc_rx_feed(void);
extern void test_keycode_report(void);
extern void test_modified_key(void);
extern void test_sec_confirm(void);
extern void test_sec_store(void);
extern void test_cdc_sec(void);
extern void test_cr_crc16(void);
extern void test_otp_proto(void);
extern void test_apdu(void);
extern void test_openpgp_do(void);
extern void test_openpgp_card(void);
extern void test_cfg_bridge(void);
extern void test_kbd_route(void);
extern void test_kbd_refresh(void);
extern void test_niphar_keymap_span(void);
extern void test_rf_channel_plan(void);
extern void test_half_state(void);
extern void test_fuse_halves(void);
extern void test_fusion_state(void);
extern void test_config_sync(void);
extern void test_fusion_route(void);
extern void test_matrix_bitmap(void);
extern void test_veille(void);
extern void test_keyboard_cadence(void);
extern void test_cadence(void);
extern void test_veille_veto(void);
extern void test_radio_owner(void);
extern void test_fusion_file(void);
extern void test_rf_status_cadence(void);
extern void test_keymap_blob_size(void);
extern void test_half_col_map(void);
extern void test_half_tx_cadence(void);
extern void test_half_tx_target(void);
extern void test_half_tx_repeat(void);
extern void test_keymap_sync_frames(void);
extern void test_keymap_sync(void);
extern void test_wake_grace(void);
extern void test_batt_calc(void);
extern void test_memlcd_model(void);
extern void test_niphar_left_pins(void);
extern void test_niphar_right_pins(void);
extern void test_conchodytes_pins(void);
extern void test_mouse_input(void);
extern void test_hid_dedup(void);
extern void test_oled_stats(void);
extern void test_link_frame(void);
extern void test_link_handshake(void);

int main(void) {
    printf("KeSp Firmware Unit Tests\n");
    printf("========================\n");

    test_key_stats();
    test_bigram();
    test_board_config();
    test_matrix_constants();
    test_matrix_flag();
    test_led_anim_constants();
    test_oled_nav();
    test_keymap_nvs();
    test_keycodes();
    test_key_features();
    test_tap_hold();
    test_tap_dance();
    test_combo();
    test_leader();
    test_rf_packet();
    test_rf_slot();
    test_heartbeat();
    test_trackpad_map();
    test_trackpad_accel_curve();
    test_trackpad_cfg();
    test_rf_pairing();
    test_rf_pairing_declared_slot();
    test_rf_signal_q255();
    test_cdc_monitor();
    test_cdc_rx_feed();
    test_keycode_report();
    test_modified_key();
    test_sec_confirm();
    test_sec_store();
    test_cdc_sec();
    test_cr_crc16();
    test_otp_proto();
    test_apdu();
    test_openpgp_do();
    test_openpgp_card();
    test_cfg_bridge();
    test_kbd_route();
    test_kbd_refresh();
    test_niphar_keymap_span();
    test_rf_channel_plan();
    test_half_state();
    test_fuse_halves();
    test_fusion_state();
    test_config_sync();
    test_fusion_route();
    test_matrix_bitmap();
    test_veille();
    test_keyboard_cadence();
    test_cadence();
    test_veille_veto();
    test_radio_owner();
    test_fusion_file();
    test_rf_status_cadence();
    test_keymap_blob_size();
    test_half_col_map();
    test_half_tx_cadence();
    test_half_tx_target();
    test_half_tx_repeat();
    test_keymap_sync_frames();
    test_keymap_sync();
    test_wake_grace();
    test_batt_calc();
    test_memlcd_model();
    test_niphar_left_pins();
    test_niphar_right_pins();
    test_conchodytes_pins();
    test_mouse_input();
    test_hid_dedup();
    test_oled_stats();
    test_link_frame();
    test_link_handshake();

    printf("\n========================================\n");
    printf("Results: %d passed, %d failed\n", _test_pass_count, _test_fail_count);
    printf("========================================\n");
    return _test_fail_count > 0 ? 1 : 0;
}
