#!/usr/bin/env python3
"""Procedural 1-bit cave-rock + Bayer-dither bitmaps for the Niphargus memlcd
cave direction. Deterministic (not random) so it's reproducible like the
project's other generated assets (gen_logo_memlcd.sh). Emits LVGL
ALPHA_1BIT C arrays (same encoding as the existing padlock/link icons in
memlcd_backend.c: MSB-first, stride = ceil(w/8))."""
import sys

W = 68

BAYER4 = [
    [0, 8, 2, 10],
    [12, 4, 14, 6],
    [3, 11, 1, 9],
    [15, 7, 13, 5],
]

def bayer_ink(x, y, density):
    """density 0..16: how many of the 16 Bayer cells are inked."""
    return BAYER4[y % 4][x % 4] < density

def teeth_depth(x, bounds, apexes):
    for i in range(len(bounds) - 1):
        a, b = bounds[i], bounds[i + 1]
        if a <= x < b:
            mid = (a + b) / 2.0
            half = (b - a) / 2.0
            d = apexes[i] * (1.0 - abs(x - mid) / half)
            return max(0, round(d))
    return 0

TOP_BOUNDS  = [0, 3, 7, 9, 13, 18, 21, 25, 30, 33, 37, 42, 45, 49, 54, 57, 61, 65, 68]
TOP_APEX    = [8, 5, 7, 4, 8, 6, 3, 8, 5, 7, 4, 8, 6, 8, 5, 3, 7, 8]
BOT_BOUNDS  = [0, 4, 8, 12, 15, 19, 24, 27, 31, 36, 39, 43, 48, 51, 55, 60, 64, 68]
BOT_APEX    = [5, 3, 6, 4, 5, 3, 6, 4, 5, 6, 3, 5, 4, 6, 3, 5, 4]

def make_grid(h):
    return [[0] * W for _ in range(h)]

def render_top(h_rock, h_shadow):
    h = h_rock + h_shadow
    g = make_grid(h)
    for x in range(W):
        d = teeth_depth(x, TOP_BOUNDS, TOP_APEX)
        d = min(d, h_rock)
        for y in range(d):
            g[y][x] = 1
    # fading dither shadow rows right under the rock: density decreases
    # with distance from the rock edge.
    for row in range(h_shadow):
        y = h_rock + row
        density = max(0, 10 - row * 4)  # 10, 6, 2, ... out of 16
        if density <= 0:
            continue
        for x in range(W):
            if bayer_ink(x, y, density):
                g[y][x] = 1
    return g

def render_bottom(h_rock, h_shadow):
    h = h_rock + h_shadow
    g = make_grid(h)
    for row in range(h_shadow):
        y = row
        density = max(0, 10 - (h_shadow - 1 - row) * 4)
        if density <= 0:
            continue
        for x in range(W):
            if bayer_ink(x, y, density):
                g[y][x] = 1
    for x in range(W):
        d = teeth_depth(x, BOT_BOUNDS, BOT_APEX)
        d = min(d, h_rock)
        for y in range(d):
            g[h - 1 - y][x] = 1
    return g

def render_dither_strip(w, h, density):
    g = [[0] * w for _ in range(h)]
    for y in range(h):
        for x in range(w):
            if bayer_ink(x, y, density):
                g[y][x] = 1
    return g

def grid_to_bits(g):
    h = len(g); w = len(g[0])
    rowbytes = (w + 7) // 8
    out = bytearray(rowbytes * h)
    for y in range(h):
        for x in range(w):
            if g[y][x]:
                out[y * rowbytes + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(out), w, h

def emit(name, g, f):
    bits, w, h = grid_to_bits(g)
    f.write(f"static const uint8_t {name}_map[] = {{\n")
    for i in range(0, len(bits), 16):
        f.write("  " + ",".join(f"0x{b:02x}" for b in bits[i:i+16]) + ",\n")
    f.write("};\n")
    f.write(f"const lv_img_dsc_t {name} = {{ .header.cf = LV_IMG_CF_ALPHA_1BIT, "
            f".header.always_zero = 0, .header.w = {w}, .header.h = {h}, "
            f".data_size = {len(bits)}, .data = {name}_map }};\n")

def ascii_preview(g):
    return "\n".join("".join("#" if c else "." for c in row) for row in g)

if __name__ == "__main__":
    top = render_top(8, 4)
    bot = render_bottom(6, 3)
    ds_small = render_dither_strip(16, 4, 8)
    ds_wide  = render_dither_strip(44, 4, 8)

    if "--preview" in sys.argv:
        print("=== rock_top ===")
        print(ascii_preview(top))
        print("=== rock_bottom ===")
        print(ascii_preview(bot))
        print("=== dither_small ===")
        print(ascii_preview(ds_small))
        sys.exit(0)

    out = sys.argv[1] if len(sys.argv) > 1 else "assets/img_rock.c"
    with open(out, "w") as f:
        f.write("/* GENERATED by tools/memlcd_sim/gen_rock.py — procedural cave-rock silhouette\n")
        f.write(" * + Bayer-dithered shadow, deterministic (not random). Do not hand-edit. */\n")
        f.write('#include "lvgl.h"\n')
        emit("img_rock_top", top, f)
        emit("img_rock_bottom", bot, f)
        emit("img_dither_small", ds_small, f)
        emit("img_dither_wide", ds_wide, f)
    print(f"wrote {out}")
