#pragma once
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Niphar_chest link, protocol version 1 — Niphar_chest docs/LINK_CONTRACT.md.
 * Re-implemented here, pinned by test_chest_proto against the contract's
 * vectors V1-V9 (generated by the chest's code, pinned on both sides). */
#define CHEST_PROTO_VERSION     1
#define CHEST_REG_SIZE          0x14
#define CHEST_REG_CHEST_LEN     0x10
#define CHEST_REG_USER_CONFIRM  0x10
#define CHEST_CONFIRM_MAGIC     0x5A
#define CHEST_STATE_SD          0x01
#define CHEST_STATE_USB         0x02
#define CHEST_STATE_READY       0x04
#define CHEST_CMD_WRBUF         0x01   /* esp_spi_slave_protocol.rst, Supported Commands */
#define CHEST_CMD_RDBUF         0x02
#define CHEST_CONFIRM_RETRY_MS  200u   /* ten chest ticks (the chest polls 0x10 every 20 ms) */
#define CHEST_LABEL_BUF         8

typedef struct {
    uint8_t  version, state;
    uint16_t pending_op;
    uint32_t confirm_count;
} chest_status_t;

typedef enum {
    CHEST_BLOCK_OK = 0,
    CHEST_BLOCK_ABSENT,        /* uniform 0x00 / 0xFF: no chest — the ordinary case, never logged */
    CHEST_BLOCK_BAD_VERSION,   /* magic ok, version != 1: refused, logged once (contract §8) */
    CHEST_BLOCK_CORRUPT,       /* magic, CRC, short read: something answers, not our chest */
} chest_block_t;

bool          chest_proto_is_absent(const uint8_t *regs, size_t len);
/* Contract §4 order: short, absent, magic, version, CRC. `out` written only on OK. */
chest_block_t chest_proto_parse(const uint8_t *regs, size_t len, chest_status_t *out);
/* True only when a press stored earlier by the chest gate (chest_gate.h)
 * should confirm THIS round's chest state: an OK block, the chest READY, a
 * real press (pressed_op != 0), and that press's op still equal to what the
 * chest currently has pending. A press taken on a non-OK round (chest
 * reboot, CORRUPT, BAD_VERSION, a skipped read) must not confirm whatever op
 * shows up at the next OK block. */
bool          chest_press_matches(uint16_t pressed_op, chest_block_t block, const chest_status_t *st);
/* Label of a chest sec_op_t code. Known codes 1-10: lookup table; 11-99: "OP nn" format;
 * >= 100: "OP ?" (controller-mandated limit). Always <= 6 characters. */
void          chest_op_label(uint16_t op, char out[CHEST_LABEL_BUF]);

/* Confirm delivery: one write, one retry after CHEST_CONFIRM_RETRY_MS if the
 * chest's counter has not moved and the same op is still pending, never a
 * third. */
typedef struct { bool armed; uint8_t writes; uint16_t op; uint32_t count0, t_ms; } chest_confirm_t;
/* A real press reached the link task. False (dropped) when nothing is pending. */
bool chest_confirm_request(chest_confirm_t *c, uint16_t pending_op, uint32_t count, uint32_t now_ms);
/* One task round. True = write CHEST_CONFIRM_MAGIC now. */
bool chest_confirm_step(chest_confirm_t *c, uint16_t pending_op, uint32_t count, uint32_t now_ms);
