#pragma once
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Niphar_chest link, protocol version 3 — Niphar_chest main/link/link_proto.h
 * (link_proto_parse_status at link_proto.c:85) and test/test_link_proto.c
 * (vectors k_vec_v1..v16, k_vec_r1..r3, k_vec_l1, k_vec_c1) at commit
 * cfd7b35. Re-implemented here, pinned by test_chest_proto against the
 * contract's vectors (generated by the chest's own code, pinned on both
 * sides). Supersedes protocol v2 (14f9352, vectors V1-V14, never flashed on
 * the bench): the 20-byte register block is replaced by the 64-byte one
 * below (account label, DMA channel signalling, TIME_VALID bit). */
#define CHEST_PROTO_VERSION     3
#define CHEST_REG_SIZE          0x40
#define CHEST_REG_INSTANCE      0x0C
#define CHEST_REG_MODE_ACTIVE   0x0D
#define CHEST_REG_LABEL_LEN     0x0E
#define CHEST_REG_OP_COUNT      0x0F
#define CHEST_REG_DMA_KIND      0x10
#define CHEST_REG_DMA_SEQ       0x11
#define CHEST_REG_DMA_LEN       0x12
#define CHEST_REG_LABEL         0x14
#define CHEST_LABEL_MAX         34
#define CHEST_REG_CRC           0x36
#define CHEST_REG_CRC_SPAN      0x36   /* CRC over 0x00..0x35 */
#define CHEST_REG_USER_CONFIRM  0x38
#define CHEST_REG_ECHO          0x39
#define CHEST_REG_MODE_REQ      0x3A
#define CHEST_REG_REQ_SEQ       0x3C   /* doorbell — DMA request number, Task 6 */
#define CHEST_CONFIRM_MAGIC     0x5A
#define CHEST_STATE_SD          0x01
#define CHEST_STATE_USB         0x02
#define CHEST_STATE_READY       0x04
#define CHEST_STATE_TIME        0x08
#define CHEST_CMD_WRBUF         0x01   /* esp_spi_slave_protocol.rst, Supported Commands */
#define CHEST_CMD_RDBUF         0x02
#define CHEST_CMD_WRDMA         0x03   /* DMA request: WRDMA then WR_END (Task 6) */
#define CHEST_CMD_RDDMA         0x04   /* DMA response: RDDMA then INT0 (Task 6) */
#define CHEST_CMD_WR_END        0x07
#define CHEST_CMD_INT0          0x08
#define CHEST_DMA_NONE          0x00
#define CHEST_DMA_LIST          0x01
#define CHEST_DMA_CODE          0x02
#define CHEST_DMA_MAX           512
#define CHEST_CONFIRM_RETRY_MS  200u   /* ten chest ticks (the chest polls 0x10 every 20 ms) */
#define CHEST_LABEL_BUF         8
/* USB mode wire values (contract §6.1) */
#define CHEST_MODE_NONE      0x00
#define CHEST_MODE_STORAGE   0x01
#define CHEST_MODE_PGP       0x02
#define CHEST_MODE_OTP       0x03
#define CHEST_MODE_FIDO      0x04
#define CHEST_MODE_OATH      0x05
#define CHEST_MODE_COUNT     6
#define CHEST_MODE_IN_FLIGHT 0xFF
#define CHEST_MODE_FAULT_READS 8     /* 2 s at the 250 ms read cadence */
#define CHEST_MODE_LABEL_BUF 5       /* 4 UNSCII characters + NUL */

/* A press as seen by the owner: the op on screen AND the arming it belongs to. */
#define CHEST_TAG(op, inst)  ((uint32_t)(op) | ((uint32_t)(inst) << 16))
#define CHEST_TAG_OP(t)      ((uint16_t)((t) & 0xFFFFu))
#define CHEST_TAG_INST(t)    ((uint8_t)(((t) >> 16) & 0xFFu))

typedef struct {
    uint8_t  version, state;
    uint16_t pending_op;
    uint32_t confirm_count;
    uint8_t  instance;       /* 0x0C */
    uint8_t  active_mode;    /* 0x0D: CHEST_MODE_* or CHEST_MODE_IN_FLIGHT */
    uint8_t  op_count;       /* 0x0F: accounts targeted — 0 none armed, 1, N (RESET) */
    uint8_t  dma_kind;       /* 0x10: CHEST_DMA_NONE/LIST/CODE */
    uint8_t  dma_seq;        /* 0x11: segment number, changes AFTER it is queued */
    uint16_t dma_len;        /* 0x12-0x13: segment length, <= CHEST_DMA_MAX */
    uint8_t  label_len;      /* 0x0E: 0..CHEST_LABEL_MAX */
    char     label[CHEST_LABEL_MAX + 1];  /* sanitized: 0x20..0x7E kept, others '?', NUL-terminated */
} chest_status_t;

typedef enum {
    CHEST_BLOCK_OK = 0,
    CHEST_BLOCK_ABSENT,        /* uniform 0x00 / 0xFF: no chest — the ordinary case, never logged */
    CHEST_BLOCK_BAD_VERSION,   /* magic ok, version != 2: refused, logged once (contract §8) */
    CHEST_BLOCK_CORRUPT,       /* magic, CRC, short read, mounted invariant: something answers, not our chest */
} chest_block_t;

bool          chest_proto_is_absent(const uint8_t *regs, size_t len);
/* Contract order: short, absent, magic, version, CRC; then label_len >
 * CHEST_LABEL_MAX (CORRUPT even with a valid CRC — a truncating parser would
 * show a name the chest never composed); then the mounted invariant
 * (USB_MOUNTED set => active mode in 0x01..0x05, else CORRUPT) — KeSp's own,
 * the chest's own link_proto_parse_status() does not reject on it. Does NOT
 * reject on the DMA fields: a bad DMA announcement must not make the whole
 * chest look absent (see chest_dma_segment_ok). `out` written only on OK. */
chest_block_t chest_proto_parse(const uint8_t *regs, size_t len, chest_status_t *out);
/* True when a DMA segment announced in `st` may be read: dma_kind is LIST or
 * CODE, and 1 <= dma_len <= CHEST_DMA_MAX. The transport (Task 6) skips the
 * read when false instead of treating the block itself as corrupt. */
bool          chest_dma_segment_ok(const chest_status_t *st);
/* The press confirms THIS round only if: OK block, READY, tag != 0, and both
 * the op AND the instance of the tag equal the block's pending op and instance. */
bool          chest_press_matches(uint32_t pressed_tag, chest_block_t block, const chest_status_t *st);
/* Label of a chest sec_op_t code. Known codes 1-10: lookup table; 11-99: "OP nn" format;
 * >= 100: "OP ?" (controller-mandated limit). Always <= 6 characters. */
void          chest_op_label(uint16_t op, char out[CHEST_LABEL_BUF]);

/* Confirm delivery: one write of {0x5A, instance}, one retry after 200 ms if the
 * counter has not moved and the same op AND instance are still pending, never a
 * third. */
typedef struct { bool armed; uint8_t writes; uint16_t op; uint8_t instance; uint32_t count0, t_ms; } chest_confirm_t;
/* A real press reached the link task. False (dropped) when nothing is pending. */
bool chest_confirm_request(chest_confirm_t *c, const chest_status_t *st, uint32_t now_ms);
/* One task round. True = write CHEST_CONFIRM_MAGIC now. */
bool chest_confirm_step(chest_confirm_t *c, const chest_status_t *st, uint32_t now_ms);

/* Mode selection (contract §6). */
uint8_t chest_mode_next(uint8_t mode);                                  /* 0->1->..->5->0; unknown -> 0 */
bool    chest_mode_needs_write(const uint8_t *regs, uint8_t wanted);    /* regs[0x12] != wanted */
typedef enum { CHEST_MODE_ARRIVED = 0, CHEST_MODE_PENDING, CHEST_MODE_FAULT } chest_mode_state_t;
typedef struct { uint8_t differ_reads; } chest_mode_track_t;
/* One OK read: ARRIVED if active == wanted; PENDING if active == IN_FLIGHT
 * (counter reset) or two known values differ for < FAULT_READS reads;
 * FAULT once they have differed for FAULT_READS consecutive reads. */
chest_mode_state_t chest_mode_track(chest_mode_track_t *t, uint8_t active, uint8_t wanted);
/* 4-character line: ARRIVED -> upper name of `active` ("" for none);
 * PENDING -> lower name of `wanted` ("" for none); FAULT -> "ERR".
 * Names: none "", storage MSC, pgp PGP, otp OTP, fido FIDO, oath OATH. */
void    chest_mode_label(chest_mode_state_t s, uint8_t active, uint8_t wanted, char out[CHEST_MODE_LABEL_BUF]);
