#pragma once
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "chest_proto.h"

/* Niphar_chest link, DMA channel — request, LIST page, CODE answer. Contract:
 * Niphar_chest main/link/link_proto.{h,c} (link_proto_pack_request,
 * link_proto_pack_list, link_proto_pack_code) and test/test_link_proto.c
 * (vectors k_vec_r1..r3, k_vec_l1, k_vec_c1, lines ~567-596) at commit
 * 440d79d (vectors identical to cfd7b35). Re-implemented here, pinned by
 * test_chest_dma against the contract's vectors (generated by the chest's
 * own code, pinned on both sides). Spec:
 * docs/superpowers/specs/2026-09-29-chest-link-v3-design.md §3. */

#define CHEST_REQ_SIZE          8
#define CHEST_REQ_LIST          0x01
#define CHEST_REQ_CODE          0x02
#define CHEST_LIST_HDR_SIZE     4
#define CHEST_LIST_OFF_TOTAL    0
#define CHEST_LIST_OFF_COUNT    1
#define CHEST_LIST_OFF_FIRST    2
#define CHEST_LIST_OFF_FLAGS    3
#define CHEST_LIST_FLAG_MORE    0x01
#define CHEST_LIST_MAX_ENTRIES  32
#define CHEST_CODE_SIZE         14

/* The 8-byte request: WRDMA then WR_END (chest_link.c, Task 6). Mirrors
 * link_proto_pack_request: cmd, arg, 4 reserved zeros, CRC16 over 0x00..0x05. */
void chest_req_pack(uint8_t out[CHEST_REQ_SIZE], uint8_t cmd, uint8_t arg);

typedef struct {
    uint8_t index;
    char    name[CHEST_LABEL_MAX + 1];   /* sanitized: 0x20..0x7E kept, others '?', NUL-terminated */
} chest_list_entry_t;

typedef struct {
    uint8_t total, count, first;
    bool    more;
    chest_list_entry_t e[CHEST_LIST_MAX_ENTRIES];
} chest_list_t;

/* Decodes a LIST page (RDDMA response, `len` from register 0x12-0x13). False
 * — `out` left untouched — on: len < header+CRC (6), len > CHEST_DMA_MAX, a
 * bad CRC, count > CHEST_LIST_MAX_ENTRIES, an entry running past len-2, a
 * name longer than CHEST_LABEL_MAX, or bytes left over between the last
 * entry and the CRC. */
bool chest_list_decode(const uint8_t *buf, uint16_t len, chest_list_t *out);

typedef struct {
    uint8_t index, digits, seconds;
    char    code[9];   /* the LAST `digits` characters of the 8-byte field, NUL-terminated */
} chest_code_t;

/* Decodes a CODE answer (RDDMA response, always CHEST_CODE_SIZE bytes). False
 * — `out` left untouched — on: len != CHEST_CODE_SIZE, a bad CRC, digits not
 * 6 or 8, a non-digit byte in the 8 code bytes, digits == 6 with a padding
 * byte (buf[2] or buf[3]) other than '0' (link_proto_pack_code always
 * memsets the field to '0' before writing the code right-justified: for a
 * 6-digit code the two leftmost bytes are ALWAYS that padding), or seconds
 * == 0 or > 30 (the chest's own sec_time_window_remaining() returns
 * 1..SEC_TIME_TOTP_STEP == 1..30: 0 would be an already-expired window and
 * anything above 30 is impossible for a real chest, both verified against
 * Niphar_chest main/security/sec_time.c at 440d79d). */
bool chest_code_decode(const uint8_t *buf, uint16_t len, chest_code_t *out);
