#pragma once
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Niphar_chest link, protocol version 2 — Niphar_chest LINK_CONTRACT.md at
 * 14f9352, vectors V1-V14. Re-implemented here, pinned by test_chest_proto
 * against the contract's vectors (generated by the chest's code, pinned on
 * both sides). */
#define CHEST_PROTO_VERSION     2
#define CHEST_REG_SIZE          0x14
#define CHEST_REG_INSTANCE      0x0C
#define CHEST_REG_MODE_ACTIVE   0x0D
#define CHEST_REG_CRC           0x0E
#define CHEST_REG_CRC_SPAN      0x0E   /* CRC over 0x00..0x0D */
#define CHEST_REG_USER_CONFIRM  0x10
#define CHEST_REG_ECHO          0x11
#define CHEST_REG_MODE_REQ      0x12
#define CHEST_CONFIRM_MAGIC     0x5A
#define CHEST_STATE_SD          0x01
#define CHEST_STATE_USB         0x02
#define CHEST_STATE_READY       0x04
#define CHEST_CMD_WRBUF         0x01   /* esp_spi_slave_protocol.rst, Supported Commands */
#define CHEST_CMD_RDBUF         0x02
#define CHEST_CONFIRM_RETRY_MS  200u   /* ten chest ticks (the chest polls 0x10 every 20 ms) */
#define CHEST_LABEL_BUF         8
/* USB mode wire values (contract §6.1) */
#define CHEST_MODE_NONE      0x00
#define CHEST_MODE_STORAGE   0x01
#define CHEST_MODE_PGP       0x02
#define CHEST_MODE_OTP       0x03
#define CHEST_MODE_FIDO      0x04
#define CHEST_MODE_OATH      0x05
#define CHEST_MODE_COUNT     6
#define CHEST_MODE_IN_FLIGHT 0xFF
#define CHEST_MODE_FAULT_READS 8     /* 2 s at the 250 ms read cadence */
#define CHEST_MODE_LABEL_BUF 5       /* 4 UNSCII characters + NUL */

/* A press as seen by the owner: the op on screen AND the arming it belongs to. */
#define CHEST_TAG(op, inst)  ((uint32_t)(op) | ((uint32_t)(inst) << 16))
#define CHEST_TAG_OP(t)      ((uint16_t)((t) & 0xFFFFu))
#define CHEST_TAG_INST(t)    ((uint8_t)(((t) >> 16) & 0xFFu))

typedef struct {
    uint8_t  version, state;
    uint16_t pending_op;
    uint32_t confirm_count;
    uint8_t  instance;       /* 0x0C */
    uint8_t  active_mode;    /* 0x0D: CHEST_MODE_* or CHEST_MODE_IN_FLIGHT */
} chest_status_t;

typedef enum {
    CHEST_BLOCK_OK = 0,
    CHEST_BLOCK_ABSENT,        /* uniform 0x00 / 0xFF: no chest — the ordinary case, never logged */
    CHEST_BLOCK_BAD_VERSION,   /* magic ok, version != 2: refused, logged once (contract §8) */
    CHEST_BLOCK_CORRUPT,       /* magic, CRC, short read, mounted invariant: something answers, not our chest */
} chest_block_t;

bool          chest_proto_is_absent(const uint8_t *regs, size_t len);
/* Contract order: short, absent, magic, version, CRC; then the mounted
 * invariant (USB_MOUNTED set => active mode in 0x01..0x05, else CORRUPT).
 * `out` written only on OK. */
chest_block_t chest_proto_parse(const uint8_t *regs, size_t len, chest_status_t *out);
/* The press confirms THIS round only if: OK block, READY, tag != 0, and both
 * the op AND the instance of the tag equal the block's pending op and instance. */
bool          chest_press_matches(uint32_t pressed_tag, chest_block_t block, const chest_status_t *st);
/* Label of a chest sec_op_t code. Known codes 1-10: lookup table; 11-99: "OP nn" format;
 * >= 100: "OP ?" (controller-mandated limit). Always <= 6 characters. */
void          chest_op_label(uint16_t op, char out[CHEST_LABEL_BUF]);

/* Confirm delivery: one write of {0x5A, instance}, one retry after 200 ms if the
 * counter has not moved and the same op AND instance are still pending, never a
 * third. */
typedef struct { bool armed; uint8_t writes; uint16_t op; uint8_t instance; uint32_t count0, t_ms; } chest_confirm_t;
/* A real press reached the link task. False (dropped) when nothing is pending. */
bool chest_confirm_request(chest_confirm_t *c, const chest_status_t *st, uint32_t now_ms);
/* One task round. True = write CHEST_CONFIRM_MAGIC now. */
bool chest_confirm_step(chest_confirm_t *c, const chest_status_t *st, uint32_t now_ms);

/* Mode selection (contract §6). */
uint8_t chest_mode_next(uint8_t mode);                                  /* 0->1->..->5->0; unknown -> 0 */
bool    chest_mode_needs_write(const uint8_t *regs, uint8_t wanted);    /* regs[0x12] != wanted */
typedef enum { CHEST_MODE_ARRIVED = 0, CHEST_MODE_PENDING, CHEST_MODE_FAULT } chest_mode_state_t;
typedef struct { uint8_t differ_reads; } chest_mode_track_t;
/* One OK read: ARRIVED if active == wanted; PENDING if active == IN_FLIGHT
 * (counter reset) or two known values differ for < FAULT_READS reads;
 * FAULT once they have differed for FAULT_READS consecutive reads. */
chest_mode_state_t chest_mode_track(chest_mode_track_t *t, uint8_t active, uint8_t wanted);
/* 4-character line: ARRIVED -> upper name of `active` ("" for none);
 * PENDING -> lower name of `wanted` ("" for none); FAULT -> "ERR".
 * Names: none "", storage MSC, pgp PGP, otp OTP, fido FIDO, oath OATH. */
void    chest_mode_label(chest_mode_state_t s, uint8_t active, uint8_t wanted, char out[CHEST_MODE_LABEL_BUF]);
