#!/usr/bin/env python3
"""Generates main/display/memlcd/memlcd_font_widths.h — the width oracle of
the left screen's layout (plan chest-link-v3 Task 8; every size of the cave
engine's ladder since plan 2026-09-30-left-screen-cave).

The host tests cannot run LVGL, so they measure text with a table of glyph
advances taken from the SAME font files the firmware compiles in:
managed_components/lvgl__lvgl/src/font/lv_font_montserrat_{12..32}.c.
For each font: the raw adv_w (1/16 px) of the printable ASCII range
0x20..0x7E, the line height, and the KERNING of that range (Montserrat kerns
by classes: a left and a right class per glyph, a value per class pair, some
of them positive — ignoring it was off by up to +4 px on a word). LVGL 8
adds the pair's value to the advance, then rounds each glyph on its own
(((adv_w + kern) + 8) >> 4, lv_font_fmt_txt.c get_glyph_dsc) — so does
memlcd_text_width(): the host measures what the panel draws, exactly.

Usage:
  gen_memlcd_font_widths.py            write the header
  gen_memlcd_font_widths.py --check    exit 1 if the committed header differs
                                       from what the font files give (the
                                       tripwire brick font-widths.sh); exit 0
                                       with a notice when the fonts are absent
"""
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
FONT_DIR = os.path.join(ROOT, "managed_components", "lvgl__lvgl", "src", "font")
OUT = os.path.join(ROOT, "main", "display", "memlcd", "memlcd_font_widths.h")
SIZES = (12, 14, 16, 18, 20, 24, 28, 32)   # the cave ladder (memlcd_cave.h)
FIRST, LAST = 0x20, 0x7E


def read_font(size):
    path = os.path.join(FONT_DIR, f"lv_font_montserrat_{size}.c")
    src = open(path, encoding="utf-8").read()
    # The first cmap must map 0x20.. contiguously onto glyph ids from 1 —
    # otherwise the id arithmetic below would read the wrong glyphs.
    m = re.search(r"\.range_start\s*=\s*(\d+),\s*\.range_length\s*=\s*(\d+),\s*"
                  r"\.glyph_id_start\s*=\s*(\d+),[^}]*?\.type\s*=\s*(\w+)", src, re.S)
    if not m:
        sys.exit(f"{path}: no cmap found")
    start, length, gid0, kind = int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4)
    if start != FIRST or start + length - 1 < LAST or kind != "LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY":
        sys.exit(f"{path}: first cmap is not a contiguous 0x20..0x7E range ({start}, {length}, {kind})")
    body = src[src.index("glyph_dsc[] = {"):]
    advs = [int(a) for a in re.findall(r"\.adv_w\s*=\s*(\d+)", body)]
    ids = range(gid0, gid0 + (LAST - FIRST + 1))
    if len(advs) <= ids[-1]:
        sys.exit(f"{path}: glyph_dsc too short")
    lh = re.search(r"\.line_height\s*=\s*(\d+)", src)
    if not lh:
        sys.exit(f"{path}: no line_height")
    kern = read_kern(path, src, ids)
    return [advs[i] for i in ids], int(lh.group(1)), kern


def c_array(src, name):
    m = re.search(name + r"\[\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        return None
    body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)
    return [int(v) for v in re.findall(r"-?\d+", body)]


def read_kern(path, src, ids):
    """(left classes, right classes, left count, right count, values) for the
    ASCII glyphs; the class maps are indexed by glyph id in the font file."""
    if not re.search(r"\.kern_classes\s*=\s*1", src) or not re.search(r"\.kern_scale\s*=\s*16\b", src):
        sys.exit(f"{path}: expected class kerning with kern_scale 16")
    left = c_array(src, "kern_left_class_mapping")
    right = c_array(src, "kern_right_class_mapping")
    vals = c_array(src, "kern_class_values")
    lc = int(re.search(r"\.left_class_cnt\s*=\s*(\d+)", src).group(1))
    rc = int(re.search(r"\.right_class_cnt\s*=\s*(\d+)", src).group(1))
    if left is None or right is None or vals is None or len(vals) != lc * rc:
        sys.exit(f"{path}: kerning tables not found or inconsistent")
    return [left[i] for i in ids], [right[i] for i in ids], lc, rc, vals


def render():
    out = []
    out.append("#pragma once")
    out.append("/* GENERATED by scripts/gen_memlcd_font_widths.py from")
    out.append(" * managed_components/lvgl__lvgl/src/font/lv_font_montserrat_{" + ",".join(str(x) for x in SIZES) + "}.c")
    out.append(" * — do not edit. Checked against the font files by")
    out.append(" * scripts/tripwire.d/font-widths.sh (fails if the table drifts).")
    out.append(" * adv_w in 1/16 px for 0x20..0x7E, plus the class kerning; LVGL adds the")
    out.append(" * kerning of the pair (this glyph, the next one) then rounds each glyph on")
    out.append(" * its own: pixels = (adv_w + kern + 8) >> 4. */")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define MEMLCD_FW_FIRST 0x{FIRST:02X}")
    out.append(f"#define MEMLCD_FW_LAST  0x{LAST:02X}")
    fonts = [(size,) + read_font(size) for size in SIZES]
    # The class maps are the same for every size (one family, one glyph
    # set): emitted once, checked here.
    kl, kr, lc, rc = fonts[0][3][0], fonts[0][3][1], fonts[0][3][2], fonts[0][3][3]
    for size, _, _, k in fonts:
        if (k[0], k[1], k[2], k[3]) != (kl, kr, lc, rc):
            sys.exit(f"montserrat_{size}: kerning classes differ from montserrat_{SIZES[0]}")
    out.append("")
    out.append("/* Kerning classes of 0x20..0x7E (0 = no kerning), shared by every size. */")
    out.append(f"#define MEMLCD_FW_KERN_RC {rc}")
    for name, cls in (("memlcd_fw_kl", kl), ("memlcd_fw_kr", kr)):
        out.append(f"static const uint8_t {name}[{len(cls)}] = {{")
        for i in range(0, len(cls), 16):
            out.append("    " + ", ".join(f"{c:2d}" for c in cls[i:i + 16]) + ",")
        out.append("};")
    for size, advs, lh, k in fonts:
        out.append("")
        out.append(f"#define MEMLCD_FW_M{size}_LINE_H {lh}")
        out.append(f"static const uint16_t memlcd_fw_m{size}[{len(advs)}] = {{")
        for i in range(0, len(advs), 8):
            chunk = advs[i:i + 8]
            chars = "".join(chr(FIRST + i + k) for k in range(len(chunk)))
            chars = chars.replace("*/", "*?").replace("\\", "\\\\")
            out.append("    " + ", ".join(f"{a:3d}" for a in chunk) + ",   /* " + chars + " */")
        out.append("};")
        vals = k[4]
        out.append(f"/* kerning, 1/16 px: [(left class - 1) * {rc} + (right class - 1)] */")
        out.append(f"static const int8_t memlcd_fw_m{size}_kv[{len(vals)}] = {{")
        for i in range(0, len(vals), rc):
            out.append("    " + ",".join(str(v) for v in vals[i:i + rc]) + ",")
        out.append("};")
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    if not all(os.path.isfile(os.path.join(FONT_DIR, f"lv_font_montserrat_{s}.c")) for s in SIZES):
        if check:
            print("font-widths: LVGL font files absent (managed_components not fetched) — not checked")
            return 0
        sys.exit("LVGL font files absent: run a build (idf.py reconfigure) first")
    text = render()
    if check:
        cur = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else ""
        if cur != text:
            print(f"{os.path.relpath(OUT, ROOT)} drifted from the LVGL font files: "
                  "rerun scripts/gen_memlcd_font_widths.py")
            return 1
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
