#!/usr/bin/env python3
"""Generates main/display/memlcd/memlcd_font_widths.h — the width oracle of
the memory-LCD's chest views (plan chest-link-v3 Task 8).

The host tests cannot run LVGL, so they measure text with a table of glyph
advances taken from the SAME font files the firmware compiles in:
managed_components/lvgl__lvgl/src/font/lv_font_montserrat_{14,24,28}.c.
For each font: the raw adv_w (1/16 px) of the printable ASCII range
0x20..0x7E, and the line height. LVGL 8 rounds each glyph's advance on its
own ((adv_w + 8) >> 4, lv_font_fmt_txt.c) — memlcd_text_width() does the same.
Kerning is ignored here; the layout keeps a 2 px margin for it.

Usage:
  gen_memlcd_font_widths.py            write the header
  gen_memlcd_font_widths.py --check    exit 1 if the committed header differs
                                       from what the font files give (the
                                       tripwire brick font-widths.sh); exit 0
                                       with a notice when the fonts are absent
"""
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
FONT_DIR = os.path.join(ROOT, "managed_components", "lvgl__lvgl", "src", "font")
OUT = os.path.join(ROOT, "main", "display", "memlcd", "memlcd_font_widths.h")
SIZES = (14, 24, 28)
FIRST, LAST = 0x20, 0x7E


def read_font(size):
    path = os.path.join(FONT_DIR, f"lv_font_montserrat_{size}.c")
    src = open(path, encoding="utf-8").read()
    # The first cmap must map 0x20.. contiguously onto glyph ids from 1 —
    # otherwise the id arithmetic below would read the wrong glyphs.
    m = re.search(r"\.range_start\s*=\s*(\d+),\s*\.range_length\s*=\s*(\d+),\s*"
                  r"\.glyph_id_start\s*=\s*(\d+),[^}]*?\.type\s*=\s*(\w+)", src, re.S)
    if not m:
        sys.exit(f"{path}: no cmap found")
    start, length, gid0, kind = int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4)
    if start != FIRST or start + length - 1 < LAST or kind != "LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY":
        sys.exit(f"{path}: first cmap is not a contiguous 0x20..0x7E range ({start}, {length}, {kind})")
    body = src[src.index("glyph_dsc[] = {"):]
    advs = [int(a) for a in re.findall(r"\.adv_w\s*=\s*(\d+)", body)]
    ids = range(gid0, gid0 + (LAST - FIRST + 1))
    if len(advs) <= ids[-1]:
        sys.exit(f"{path}: glyph_dsc too short")
    lh = re.search(r"\.line_height\s*=\s*(\d+)", src)
    if not lh:
        sys.exit(f"{path}: no line_height")
    return [advs[i] for i in ids], int(lh.group(1))


def render():
    out = []
    out.append("#pragma once")
    out.append("/* GENERATED by scripts/gen_memlcd_font_widths.py from")
    out.append(" * managed_components/lvgl__lvgl/src/font/lv_font_montserrat_{14,24,28}.c")
    out.append(" * — do not edit. Checked against the font files by")
    out.append(" * scripts/tripwire.d/font-widths.sh (fails if the table drifts).")
    out.append(" * adv_w in 1/16 px for 0x20..0x7E; LVGL rounds each glyph on its own:")
    out.append(" * pixels = (adv_w + 8) >> 4. */")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define MEMLCD_FW_FIRST 0x{FIRST:02X}")
    out.append(f"#define MEMLCD_FW_LAST  0x{LAST:02X}")
    for size in SIZES:
        advs, lh = read_font(size)
        out.append("")
        out.append(f"#define MEMLCD_FW_M{size}_LINE_H {lh}")
        out.append(f"static const uint16_t memlcd_fw_m{size}[{len(advs)}] = {{")
        for i in range(0, len(advs), 8):
            chunk = advs[i:i + 8]
            chars = "".join(chr(FIRST + i + k) for k in range(len(chunk)))
            chars = chars.replace("*/", "*?").replace("\\", "\\\\")
            out.append("    " + ", ".join(f"{a:3d}" for a in chunk) + ",   /* " + chars + " */")
        out.append("};")
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    if not all(os.path.isfile(os.path.join(FONT_DIR, f"lv_font_montserrat_{s}.c")) for s in SIZES):
        if check:
            print("font-widths: LVGL font files absent (managed_components not fetched) — not checked")
            return 0
        sys.exit("LVGL font files absent: run a build (idf.py reconfigure) first")
    text = render()
    if check:
        cur = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else ""
        if cur != text:
            print(f"{os.path.relpath(OUT, ROOT)} drifted from the LVGL font files: "
                  "rerun scripts/gen_memlcd_font_widths.py")
            return 1
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
